name: CD Production

on:
  push:
    branches: [ main ]

jobs:
  quality-check-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mlflow scikit-learn pandas

      # --- LE QUALITY GATE (Guard Gate obligatoire pour la Prod) ---
      - name: Run Quality Gate
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/Yannos95/MLOps-Final-Project.mlflow
          PYTHONPATH: .
        run: python tests/quality_gate.py

      # --- SI LE GATE PASSE (Success), ON BUILD & PUSH ---
      - name: Login to GHCR
        if: success()
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repo name
        run: echo "REPO_LC=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      - name: Build and Push Prod Image
        if: success()
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}/iris-app:latest
            ghcr.io/${{ env.REPO_LC }}/iris-app:prod